const RIDDLE_CATEGORIES = {
  short:        { name: "Short Riddle",        icon: "🧩", triesBeforeHint: [3],   triesBeforeReveal: 6 },
  trick:        { name: "Trick Riddle",        icon: "🎭", triesBeforeHint: [3],   triesBeforeReveal: 6 },
  story:        { name: "Story Riddle",        icon: "📖", triesBeforeHint: [3, 6], triesBeforeReveal: 9 },
  logic:        { name: "Number/Logic Riddle", icon: "🔢", triesBeforeHint: [3, 6], triesBeforeReveal: 9 },
  situational:  { name: "Situational Riddle",  icon: "🔍", triesBeforeHint: [3, 6], triesBeforeReveal: 9 }
};

const riddles = [

/* ============================================================ */
/* SHORT RIDDLE (50)                                             */
/* ============================================================ */
{ id: "short_001", category: "short", prompt: "What has to be broken before you can use it?", answers: ["egg", "an egg"], hints: ["You crack it open for breakfast."], coinReward: 10 },
{ id: "short_002", category: "short", prompt: "I speak without a mouth and hear without ears. I have no body, but I come alive with wind. What am I?", answers: ["echo", "an echo"], hints: ["Shout in a canyon and you'll hear one."], coinReward: 10 },
{ id: "short_003", category: "short", prompt: "The more you take, the more you leave behind. What am I?", answers: ["footsteps", "footprints"], hints: ["Think about walking on sand."], coinReward: 10 },
{ id: "short_004", category: "short", prompt: "What has keys but can't open locks?", answers: ["piano", "a piano"], hints: ["It also has a keyboard."], coinReward: 10 },
{ id: "short_005", category: "short", prompt: "What gets wetter the more it dries?", answers: ["towel", "a towel"], hints: ["You use it after a shower."], coinReward: 10 },
{ id: "short_006", category: "short", prompt: "What has a neck but no head?", answers: ["bottle", "a bottle"], hints: ["You'd find it on a shelf full of drinks."], coinReward: 10 },
{ id: "short_007", category: "short", prompt: "What has hands but can't clap?", answers: ["clock", "a clock"], hints: ["It's on the wall, telling you something."], coinReward: 10 },
{ id: "short_008", category: "short", prompt: "What can travel around the world while staying in a corner?", answers: ["stamp", "a stamp"], hints: ["It goes on the corner of an envelope."], coinReward: 10 },
{ id: "short_009", category: "short", prompt: "What has one eye but can't see?", answers: ["needle", "a needle"], hints: ["Thread goes through it."], coinReward: 10 },
{ id: "short_010", category: "short", prompt: "What comes down but never goes up?", answers: ["rain"], hints: ["It falls from clouds."], coinReward: 10 },
{ id: "short_011", category: "short", prompt: "What can you catch but not throw?", answers: ["a cold", "cold"], hints: ["You catch it when you're sick."], coinReward: 10 },
{ id: "short_012", category: "short", prompt: "What has a thumb and four fingers but is not alive?", answers: ["glove", "a glove"], hints: ["You wear it in winter."], coinReward: 10 },
{ id: "short_013", category: "short", prompt: "What has legs but doesn't walk?", answers: ["a table", "table", "a chair", "chair"], hints: ["You'd find it in a kitchen or dining room."], coinReward: 10 },
{ id: "short_014", category: "short", prompt: "What can fill a room but takes up no space?", answers: ["light"], hints: ["Flip a switch and it fills the room instantly."], coinReward: 10 },
{ id: "short_015", category: "short", prompt: "What goes up but never comes down?", answers: ["your age", "age"], hints: ["It increases every birthday."], coinReward: 10 },
{ id: "short_016", category: "short", prompt: "What has many teeth but cannot bite?", answers: ["a comb", "comb"], hints: ["You use it to fix your hair."], coinReward: 10 },
{ id: "short_017", category: "short", prompt: "What has a ring but no finger?", answers: ["a telephone", "telephone", "phone"], hints: ["It used to ring loudly before smartphones."], coinReward: 10 },
{ id: "short_018", category: "short", prompt: "What can you break without ever touching it?", answers: ["a promise", "promise"], hints: ["It's something you make with words, not hands."], coinReward: 10 },
{ id: "short_019", category: "short", prompt: "What has words but never speaks?", answers: ["a book", "book"], hints: ["You read it, page by page."], coinReward: 10 },
{ id: "short_020", category: "short", prompt: "What has a head and a tail but no body?", answers: ["a coin", "coin"], hints: ["You'd flip it to make a decision."], coinReward: 10 },
{ id: "short_021", category: "short", prompt: "What can you hold without ever touching it?", answers: ["your breath", "breath"], hints: ["You do it before diving underwater."], coinReward: 10 },
{ id: "short_022", category: "short", prompt: "What has branches but no fruit, trunk, or leaves?", answers: ["a bank", "bank"], hints: ["You might have an account there."], coinReward: 10 },
{ id: "short_023", category: "short", prompt: "What has a heart that doesn't beat?", answers: ["an artichoke", "artichoke"], hints: ["It's a vegetable with a soft center."], coinReward: 10 },
{ id: "short_024", category: "short", prompt: "What is full of holes but still holds water?", answers: ["a sponge", "sponge"], hints: ["You use it to clean dishes."], coinReward: 10 },
{ id: "short_025", category: "short", prompt: "What kind of room has no doors or windows?", answers: ["a mushroom", "mushroom"], hints: ["It grows in damp, shady places."], coinReward: 10 },
{ id: "short_026", category: "short", prompt: "What has feet but cannot walk?", answers: ["a bed", "bed"], hints: ["You sleep on it every night."], coinReward: 10 },
{ id: "short_027", category: "short", prompt: "What kind of coat can only be put on when wet?", answers: ["a coat of paint", "paint"], hints: ["It's used to change the color of a wall."], coinReward: 10 },
{ id: "short_028", category: "short", prompt: "What invention lets you look right through a wall?", answers: ["a window", "window"], hints: ["It lets light and sight both through."], coinReward: 10 },
{ id: "short_029", category: "short", prompt: "What goes through cities and fields but never moves?", answers: ["a road", "road", "a highway", "highway"], hints: ["Cars travel along it all day."], coinReward: 10 },
{ id: "short_030", category: "short", prompt: "What can you serve but never eat?", answers: ["a ball", "ball"], hints: ["Think about tennis or volleyball, not dinner."], coinReward: 10 },
{ id: "short_031", category: "short", prompt: "What has a face but no eyes, hands but no arms?", answers: ["a clock", "clock", "a watch", "watch"], hints: ["It's on the wall, telling you the time."], coinReward: 10 },
{ id: "short_032", category: "short", prompt: "What can you not hold for more than a few minutes even though it's light as a feather?", answers: ["your breath", "breath"], hints: ["Try holding it while swimming underwater."], coinReward: 10 },
{ id: "short_033", category: "short", prompt: "What has an ear but cannot hear?", answers: ["corn", "a corn", "corn on the cob"], hints: ["It grows on a stalk in a field."], coinReward: 10 },
{ id: "short_034", category: "short", prompt: "What can you break with just one word?", answers: ["silence"], hints: ["Say anything, and it's gone."], coinReward: 10 },
{ id: "short_035", category: "short", prompt: "What has a golden head and a golden tail but no golden body?", answers: ["a coin", "coin"], hints: ["Flip it to decide something."], coinReward: 10 },
{ id: "short_036", category: "short", prompt: "What building has thousands of stories but never gets old?", answers: ["a library", "library"], hints: ["Think of 'stories' two different ways."], coinReward: 10 },
{ id: "short_037", category: "short", prompt: "What kind of tree can you carry in your hand?", answers: ["a palm", "palm"], hints: ["Look down at your own hand."], coinReward: 10 },
{ id: "short_038", category: "short", prompt: "What has a bottom at the top?", answers: ["your legs", "legs"], hints: ["Think about where your legs meet your body."], coinReward: 10 },
{ id: "short_039", category: "short", prompt: "What can you not see, but is always in front of you?", answers: ["the future"], hints: ["It hasn't happened yet."], coinReward: 10 },
{ id: "short_040", category: "short", prompt: "What kind of band never plays music?", answers: ["a rubber band", "rubber band"], hints: ["You'd use it to hold papers together."], coinReward: 10 },
{ id: "short_041", category: "short", prompt: "What goes up and down but never moves?", answers: ["stairs", "a staircase"], hints: ["You'd climb it to reach the next floor."], coinReward: 10 },
{ id: "short_042", category: "short", prompt: "What can you give away and still keep?", answers: ["your word", "a cold", "your smile"], hints: ["Think of a promise, not an object."], coinReward: 10 },
{ id: "short_043", category: "short", prompt: "What has a spine but no bones, and pages but isn't a diary?", answers: ["a book", "book"], hints: ["You read it cover to cover."], coinReward: 10 },
{ id: "short_044", category: "short", prompt: "What kind of cup doesn't hold water?", answers: ["a cupcake", "cupcake"], hints: ["It's a sweet treat, not a drink."], coinReward: 10 },
{ id: "short_045", category: "short", prompt: "What has a bank but no money?", answers: ["a river", "river"], hints: ["Water flows along its edges."], coinReward: 10 },
{ id: "short_046", category: "short", prompt: "What can you not use until you break it?", answers: ["an egg", "egg", "a record"], hints: ["Think of breakfast, not sports."], coinReward: 10 },
{ id: "short_047", category: "short", prompt: "What is always coming but never arrives?", answers: ["tomorrow"], hints: ["It's always one day away."], coinReward: 10 },
{ id: "short_048", category: "short", prompt: "What has one head, one foot, and four legs?", answers: ["a bed", "bed"], hints: ["You sleep on it every night."], coinReward: 10 },
{ id: "short_049", category: "short", prompt: "What kind of key opens no locks but unlocks a song?", answers: ["a musical key", "musical key", "a piano key"], hints: ["Think of sheet music, not a keyring."], coinReward: 10 },
{ id: "short_050", category: "short", prompt: "What can you not put back once it's broken?", answers: ["a promise", "trust"], hints: ["It's not physical — it's between people."], coinReward: 10 },

/* ============================================================ */
/* TRICK RIDDLE (30)                                             */
/* ============================================================ */
{ id: "trick_001", category: "trick", prompt: "How many months have 28 days?", answers: ["all of them", "12", "twelve"], hints: ["Think about every month, not just February."], coinReward: 10 },
{ id: "trick_002", category: "trick", prompt: "A farmer has 17 sheep. All but 9 die. How many sheep are left?", answers: ["9", "nine"], hints: ["Read the sentence again, slowly."], coinReward: 10 },
{ id: "trick_003", category: "trick", prompt: "What word becomes shorter when you add two letters to it?", answers: ["short"], hints: ["Add 'er' to the word itself."], coinReward: 10 },
{ id: "trick_004", category: "trick", prompt: "If a plane crashes exactly on the border of the US and Canada, where do they bury the survivors?", answers: ["nowhere, survivors aren't buried", "you don't bury survivors"], hints: ["Focus on the word 'survivors.'"], coinReward: 10 },
{ id: "trick_005", category: "trick", prompt: "How many times can you subtract 5 from 25?", answers: ["once", "one time", "1"], hints: ["After the first time, it's no longer 25."], coinReward: 10 },
{ id: "trick_006", category: "trick", prompt: "What has 13 hearts but no other organs?", answers: ["a deck of cards", "deck of cards"], hints: ["Think of a suit, not an organ."], coinReward: 10 },
{ id: "trick_007", category: "trick", prompt: "A man is looking at a portrait. Someone asks who it is. He says: 'Brothers and sisters I have none, but that man's father is my father's son.' Who is in the portrait?", answers: ["his son"], hints: ["'My father's son' with no siblings means... him."], coinReward: 10 },
{ id: "trick_008", category: "trick", prompt: "What can you never eat for breakfast?", answers: ["lunch", "dinner"], hints: ["Think about the order meals happen in."], coinReward: 10 },
{ id: "trick_009", category: "trick", prompt: "If there are three apples and you take away two, how many do you have?", answers: ["two", "2"], hints: ["Focus on 'you' — how many did YOU take?"], coinReward: 10 },
{ id: "trick_010", category: "trick", prompt: "A rooster lays an egg on the very top of a barn roof. Which way does it roll?", answers: ["neither, roosters don't lay eggs", "roosters don't lay eggs"], hints: ["Think about the rooster, not the roof."], coinReward: 10 },
{ id: "trick_011", category: "trick", prompt: "What five-letter word becomes shorter when you add two letters to it?", answers: ["short"], hints: ["It's the same trick as before — think literally."], coinReward: 10 },
{ id: "trick_012", category: "trick", prompt: "Two mothers and two daughters go out to eat. Everyone gets one burger, and there are only 3 burgers total. How is that possible?", answers: ["grandmother, mother, daughter", "3 generations"], hints: ["There are only 3 people, not 4."], coinReward: 10 },
{ id: "trick_013", category: "trick", prompt: "What can you hold in your left hand but never in your right hand?", answers: ["your right hand", "right hand"], hints: ["Try it — literally."], coinReward: 10 },
{ id: "trick_014", category: "trick", prompt: "I am an odd number. Take away one letter and I become even. What number am I?", answers: ["seven"], hints: ["Remove the 's' and read what's left."], coinReward: 10 },
{ id: "trick_015", category: "trick", prompt: "How far can a dog run into the woods?", answers: ["halfway", "halfway, then it's running out"], hints: ["After the halfway point, it's running back out."], coinReward: 10 },
{ id: "trick_016", category: "trick", prompt: "What did the ocean say to the shore?", answers: ["nothing, it just waved"], hints: ["Think about what oceans do to shorelines."], coinReward: 10 },
{ id: "trick_017", category: "trick", prompt: "How many seconds are there in a year?", answers: ["12", "twelve"], hints: ["January 2nd, February 2nd... count the 2nds."], coinReward: 10 },
{ id: "trick_018", category: "trick", prompt: "A woman shoots her husband, then holds him underwater for 5 minutes, then hangs him. Right after, they enjoy a lovely dinner. How?", answers: ["she took a photo, developed it, and hung it to dry", "photography"], hints: ["She's a photographer."], coinReward: 10 },
{ id: "trick_019", category: "trick", prompt: "What is at the end of a rainbow?", answers: ["the letter w"], hints: ["Spell the word 'rainbow.'"], coinReward: 10 },
{ id: "trick_020", category: "trick", prompt: "You're in a race and you pass the person in 2nd place. What place are you in now?", answers: ["2nd", "second"], hints: ["You took their spot — you didn't pass 1st place."], coinReward: 10 },
{ id: "trick_021", category: "trick", prompt: "What occurs once in a minute, twice in a moment, but never in a thousand years?", answers: ["the letter m"], hints: ["Count the letter 'm' in each word."], coinReward: 10 },
{ id: "trick_022", category: "trick", prompt: "If you have 6 apples and take away 4, how many do you have?", answers: ["4", "four"], hints: ["Same trick as before — focus on 'you take.'"], coinReward: 10 },
{ id: "trick_023", category: "trick", prompt: "A cowboy rode into town on Friday, stayed three days, and left on Friday. How?", answers: ["his horse is named friday", "friday is the horse's name"], hints: ["'Friday' might not be the day of the week."], coinReward: 10 },
{ id: "trick_024", category: "trick", prompt: "What word is spelled incorrectly in every single dictionary?", answers: ["incorrectly"], hints: ["Look at the word 'incorrectly' itself."], coinReward: 10 },
{ id: "trick_025", category: "trick", prompt: "Before Mount Everest was discovered, what was the tallest mountain in the world?", answers: ["mount everest", "everest"], hints: ["Discovery doesn't change what already existed."], coinReward: 10 },
{ id: "trick_026", category: "trick", prompt: "What can you catch, but also never actually hold?", answers: ["your breath", "breath"], hints: ["Think about swimming or being startled."], coinReward: 10 },
{ id: "trick_027", category: "trick", prompt: "There's a one-story house where everything is yellow. What color are the stairs?", answers: ["there are no stairs", "no stairs, it's one story"], hints: ["Re-read 'one-story' carefully."], coinReward: 10 },
{ id: "trick_028", category: "trick", prompt: "Which is heavier: a pound of feathers or a pound of bricks?", answers: ["neither, they're equal", "the same", "equal"], hints: ["They're both measured the same way — a pound."], coinReward: 10 },
{ id: "trick_029", category: "trick", prompt: "What can you add to a bucket of water to make it weigh less?", answers: ["holes"], hints: ["Think about what would let water escape."], coinReward: 10 },
{ id: "trick_030", category: "trick", prompt: "If two's company and three's a crowd, what are four and five?", answers: ["nine", "9"], hints: ["Add the numbers together literally."], coinReward: 10 },

/* ============================================================ */
/* STORY RIDDLE (25)                                             */
/* ============================================================ */
{ id: "story_001", category: "story", story: "You come to a fork in the road deep in an unfamiliar forest. Two guards stand watch, one at each path. You're told one guard always tells the truth, and the other always lies — but you don't know which is which. You may ask only one question, to only one guard, to find the path that leads home.", prompt: "What single question do you ask to be sure you pick the correct path?", answers: ["ask either guard what the other guard would say", "ask one guard what the other one would say", "what would the other guard say"], hints: ["Whichever guard you ask, imagine what their answer reveals about the other guard.", "Ask about the OTHER guard's answer, then pick the opposite path."], coinReward: 25 },
{ id: "story_002", category: "story", story: "Long ago, a great stone guardian stood at the gates of an ancient city, refusing to let anyone pass until they answered its riddle. Travelers who failed were never seen again.", prompt: "What walks on four legs in the morning, two legs at noon, and three legs in the evening?", answers: ["a human", "a person", "man", "humans"], hints: ["Think about a single lifetime, from beginning to end.", "'Morning,' 'noon,' and 'evening' represent stages of life — crawling, walking, using a cane."], coinReward: 25 },
{ id: "story_003", category: "story", story: "An old sailor once told a young apprentice about the strangest tool aboard any ship — something the crew is always eager to throw overboard, yet just as eager to pull back up.", prompt: "What do sailors throw away when they want to use it, but pull back in when they don't?", answers: ["an anchor", "anchor"], hints: ["Think about what keeps a ship in place.", "It goes into the water to be useful, and comes out when the ship is ready to move."], coinReward: 25 },
{ id: "story_004", category: "story", story: "A king once faced a rebellion and turned to his wisest advisor for help ending it peacefully. The advisor said the answer lay in an old riddle: 'The one who makes it sells it. The one who buys it never uses it. The one who uses it never even sees it.'", prompt: "What is the advisor describing?", answers: ["a coffin", "coffin"], hints: ["Think about something made for someone who has already passed away.", "The person 'using' it isn't alive to see it."], coinReward: 25 },
{ id: "story_005", category: "story", story: "A forester once taught a young apprentice how to tell a tree's age without counting a single leaf or measuring its height — just by cutting it down and looking inside.", prompt: "What does a tree have that has many rings but no fingers, each one telling a chapter of its life?", answers: ["its rings", "tree rings", "growth rings"], hints: ["Look at a fresh tree stump after it's been cut.", "Each ring marks one year of growth."], coinReward: 25 },
{ id: "story_006", category: "story", story: "A group of children were digging in an empty lot, trying to build the biggest hole they could. One of them made a strange observation about their work.", prompt: "What gets bigger the more you take away from it?", answers: ["a hole", "hole", "a pit", "pit"], hints: ["Think about what you're actually doing when you dig.", "Removing dirt makes the hole itself larger, not smaller."], coinReward: 25 },
{ id: "story_007", category: "story", story: "In an old cabin with no electricity, a grandmother lit a small object each night before bed. She told her grandchildren it was slowly dying with every hour it stayed lit — the only thing in the house that got shorter the more useful it was.", prompt: "What is the grandmother lighting each night?", answers: ["a candle", "candle"], hints: ["It gives off light and melts as it burns.", "The longer it burns, the shorter it gets."], coinReward: 25 },
{ id: "story_008", category: "story", story: "A boy noticed something following him everywhere during the day — copying every move he made, but disappearing the moment the sun went down or he stepped into even light from every direction.", prompt: "What was following the boy?", answers: ["his shadow", "a shadow", "shadow"], hints: ["It only appears when there's a light source behind you.", "It mimics your exact movements silently."], coinReward: 25 },
{ id: "story_009", category: "story", story: "An old cartographer once boasted to his apprentice that he had captured every mountain, river, and city in the entire world — and could fold the whole thing up to fit inside his coat pocket.", prompt: "What had the cartographer created?", answers: ["a map", "map"], hints: ["It represents the real world but isn't the real world itself.", "You unfold it to see the whole world at once, small enough to carry."], coinReward: 25 },
{ id: "story_010", category: "story", story: "A blacksmith described his most valuable tool to an apprentice: something that could destroy a whole forest in hours, yet also keep a family warm and fed all winter, depending entirely on how it was used.", prompt: "What is the blacksmith describing?", answers: ["fire", "a fire"], hints: ["It can be either destructive or life-sustaining.", "Think of something you'd find in both a forge and a wildfire."], coinReward: 25 },
{ id: "story_011", category: "story", story: "A traveling merchant claimed to sell something owned by every person he ever met, yet none of them had ever seen it, touched it, or been able to hand it directly to someone else without it changing entirely.", prompt: "What was the merchant talking about?", answers: ["a name", "your name", "name"], hints: ["Everyone has one, but you can't hold it in your hands.", "When someone else says it, it becomes theirs to use, not yours."], coinReward: 25 },
{ id: "story_012", category: "story", story: "A philosopher once told his students about a thief that steals from everyone equally, rich and poor alike, and can never be caught, locked up, or returned no matter how hard anyone tries.", prompt: "What is the philosopher describing?", answers: ["time"], hints: ["It passes the same for every person, no matter their wealth.", "You can spend it, waste it, or save it — but never get it back."], coinReward: 25 },
{ id: "story_013", category: "story", story: "A hiker shouted into a canyon just to hear something shout back the exact same words a moment later, though no one else was around for miles.", prompt: "What answered the hiker back?", answers: ["an echo", "echo"], hints: ["Sound bounces off canyon walls.", "It repeats exactly what you say, word for word."], coinReward: 25 },
{ id: "story_014", category: "story", story: "A queen kept an object in her chamber that showed her exact likeness every single day, yet the object itself never aged a single day in fifty years.", prompt: "What object showed the queen her reflection?", answers: ["a mirror", "mirror"], hints: ["You look into it to see yourself.", "It's made of glass with a reflective backing."], coinReward: 25 },
{ id: "story_015", category: "story", story: "A locksmith told his apprentice about a small object that could open a thousand different doors, yet was itself useless without knowing exactly which door it belonged to.", prompt: "What is the locksmith describing?", answers: ["a key", "key"], hints: ["It fits into a lock.", "Each one usually only opens one specific door."], coinReward: 25 },
{ id: "story_016", category: "story", story: "A king asked each of his three daughters how much they loved him. Two answered with grand comparisons to gold and jewels. The youngest said she loved him 'as meat loves salt.' Furious, he banished her — until his feast the next day was cooked entirely without one ingredient, and every dish tasted unbearably bland.", prompt: "What ingredient was missing from the king's feast?", answers: ["salt"], hints: ["Think about what the youngest daughter compared her love to.", "It's a seasoning that makes bland food taste right."], coinReward: 25 },
{ id: "story_017", category: "story", story: "A sailor described something that could fill his ship's sails and carry it across the ocean, yet could never be seen, caught, or held in any net.", prompt: "What is the sailor describing?", answers: ["wind", "the wind"], hints: ["You feel it, but you can't see it.", "It's what pushes sailboats across the water."], coinReward: 25 },
{ id: "story_018", category: "story", story: "After a storm, a child pointed at something arching across the sky, insisting it was made of every color at once, yet the moment she ran toward it, it seemed to move just as far away.", prompt: "What did the child see in the sky?", answers: ["a rainbow", "rainbow"], hints: ["It appears after rain, when the sun comes back out.", "It has seven colors arranged in an arc."], coinReward: 25 },
{ id: "story_019", category: "story", story: "A monk told his student about something so powerful that a single spoken word could destroy it instantly, no matter how long it had lasted in a room.", prompt: "What is the monk describing?", answers: ["silence"], hints: ["Think about what happens the moment someone starts talking.", "It's the absence of sound."], coinReward: 25 },
{ id: "story_020", category: "story", story: "A soldier stationed far from home wrote something every week, sealed it in an envelope, and watched it travel hundreds of miles by hand to reach the one person who mattered most — though the soldier himself never went anywhere.", prompt: "What did the soldier send home each week?", answers: ["a letter", "letter"], hints: ["It's written on paper and mailed.", "It's how people used to stay in touch before phones."], coinReward: 25 },
{ id: "story_021", category: "story", story: "In a small village, one object was struck instead of spoken to, and yet everyone in town understood exactly what it meant the moment they heard its voice.", prompt: "What object could 'speak' to an entire village without saying a word?", answers: ["a bell", "bell"], hints: ["You ring it, you don't talk to it.", "Church towers often have one."], coinReward: 25 },
{ id: "story_022", category: "story", story: "A lost explorer carried a small object that always pointed the same direction no matter how many times he turned it, spun it, or tried to trick it.", prompt: "What did the explorer carry to keep from getting lost?", answers: ["a compass", "compass"], hints: ["It has a needle that always points north.", "Explorers and hikers use it for navigation."], coinReward: 25 },
{ id: "story_023", category: "story", story: "An astronomer described something that changes shape every night without ever actually changing at all, growing from a sliver to a full circle and back again over about a month.", prompt: "What is the astronomer describing?", answers: ["the moon", "moon"], hints: ["Look up at the night sky.", "It goes through phases — crescent, full, new."], coinReward: 25 },
{ id: "story_024", category: "story", story: "A traveler crossing a frozen lake was warned about something that felt as solid as stone under his boots, yet could turn back into the very thing it once was with just a little warmth.", prompt: "What was the traveler walking on?", answers: ["ice"], hints: ["It forms when water gets cold enough.", "It melts back into water when it warms up."], coinReward: 25 },
{ id: "story_025", category: "story", story: "A librarian described an object filled with countless voices from people who had died centuries ago, yet anyone could still hear exactly what they had to say by opening its cover.", prompt: "What object is the librarian describing?", answers: ["a book", "book"], hints: ["You read it page by page.", "Authors' words live on inside it long after they're gone."], coinReward: 25 },

/* ============================================================ */
/* NUMBER/LOGIC RIDDLE (30)                                      */
/* ============================================================ */
{ id: "logic_001", category: "logic", prompt: "A man is 32 years old, but he's only had 8 birthdays. How is this possible?", answers: ["he was born on february 29th", "born on leap day", "he's born on a leap year, february 29"], hints: ["Think about a date that doesn't occur every year.", "It only happens once every 4 years."], coinReward: 20 },
{ id: "logic_002", category: "logic", prompt: "If you multiply this number by any other number, the answer will always be the same. What number is it?", answers: ["0", "zero"], hints: ["Think about a number that 'cancels out' everything.", "Anything times this number equals itself."], coinReward: 20 },
{ id: "logic_003", category: "logic", prompt: "What three positive whole numbers give the exact same result whether you add them together or multiply them together?", answers: ["1, 2, 3", "1 2 3", "one two three"], hints: ["Try small numbers close together, starting from 1.", "1+2+3 and 1×2×3 both equal the same thing."], coinReward: 20 },
{ id: "logic_004", category: "logic", prompt: "Using only addition and eight 8's total, how do you reach exactly 1000?", answers: ["888 + 88 + 8 + 8 + 8", "888+88+8+8+8"], hints: ["Start with a 3-digit number made of 8's, then a 2-digit one.", "888 + 88 gets you most of the way — what's left needs single 8's."], coinReward: 20 },
{ id: "logic_005", category: "logic", prompt: "There are 5 apples in a basket and 5 kids in the room. How do you give each kid one apple, while still leaving one apple in the basket?", answers: ["give the last kid the basket with the apple still in it", "give the basket with the last apple to the last kid"], hints: ["The last apple doesn't have to leave the basket.", "One of the kids can just receive the basket itself."], coinReward: 20 },
{ id: "logic_006", category: "logic", prompt: "What number comes next in this sequence: 2, 6, 12, 20, 30, ?", answers: ["42"], hints: ["Look at the difference between each number and the next.", "Each number is n × (n+1) for n = 1, 2, 3..."], coinReward: 20 },
{ id: "logic_007", category: "logic", prompt: "Think of any number. Double it, add 6, divide the result by 2, then subtract your original number. What number do you always end up with, no matter what you started with?", answers: ["3", "three"], hints: ["Try it with a couple of different starting numbers and compare.", "The starting number always cancels itself out."], coinReward: 20 },
{ id: "logic_008", category: "logic", prompt: "A clock reads exactly 3:15. What is the angle, in degrees, between the hour and minute hands?", answers: ["7.5", "7.5 degrees"], hints: ["The minute hand at 15 minutes points to exactly 90°.", "The hour hand has also crept a bit past the 3 by 3:15 — it's not still exactly at 90° itself."], coinReward: 20 },
{ id: "logic_009", category: "logic", prompt: "You have two ropes that each take exactly 60 minutes to burn, but burn unevenly along their length. You light rope A at both ends and rope B at one end, all at the same moment. The instant rope A finishes burning, you light rope B's other end too. How many total minutes will have passed once rope B finishes burning completely?", answers: ["45", "45 minutes"], hints: ["Rope A, lit at both ends, finishes in exactly half its normal time.", "Once rope B is lit from both ends, however much of it is left burns in half the remaining time."], coinReward: 20 },
{ id: "logic_010", category: "logic", prompt: "A snail is at the bottom of a 10-foot well. Each day it climbs 3 feet, but each night it slides back down 2 feet. How many days does it take to reach the top?", answers: ["8", "8 days"], hints: ["It gains a net 1 foot per day — but the day it finally reaches the top, it doesn't slide back.", "Track its height carefully day by day near the end."], coinReward: 20 },
{ id: "logic_011", category: "logic", prompt: "In a 12-hour period, how many times do a clock's hour and minute hands overlap exactly?", answers: ["11", "11 times"], hints: ["It's not 12 — think about what happens right around 12:00 itself.", "The hands overlap slightly less often than once per hour."], coinReward: 20 },
{ id: "logic_012", category: "logic", prompt: "A bat and a ball cost $1.10 total. The bat costs exactly $1.00 more than the ball. How much does the ball cost?", answers: ["$0.05", "5 cents", "0.05", "five cents"], hints: ["The answer isn't 10 cents — check the math against the $1.00 difference.", "If the ball is x, the bat is x + $1.00, and together they total $1.10."], coinReward: 20 },
{ id: "logic_013", category: "logic", prompt: "If 5 machines take 5 minutes to make 5 widgets, how long would it take 100 machines to make 100 widgets?", answers: ["5", "5 minutes"], hints: ["Each machine makes its own widget at the same rate, independently.", "More machines making more widgets doesn't mean it takes longer."], coinReward: 20 },
{ id: "logic_014", category: "logic", prompt: "A patch of lily pads on a lake doubles in size every single day. It takes 48 days for the patch to cover the entire lake. On what day was the lake exactly half covered?", answers: ["47", "day 47"], hints: ["If it doubles every day, work backward one day from full coverage.", "Half of the lake, doubled once, equals the whole lake."], coinReward: 20 },
{ id: "logic_015", category: "logic", prompt: "What is the next number in this sequence: 1, 1, 2, 3, 5, 8, 13, ?", answers: ["21"], hints: ["Each number is the sum of the two before it.", "13 + 8 = ?"], coinReward: 20 },
{ id: "logic_016", category: "logic", prompt: "I'm thinking of a number. Add 15 to it, then divide the result by 3, and you get 10. What's my number?", answers: ["15"], hints: ["Work backward: 10 × 3 gives you the number before it was divided.", "Then subtract the 15 that was added at the start."], coinReward: 20 },
{ id: "logic_017", category: "logic", prompt: "How many total squares (of every possible size, not just the 64 single ones) are there on a standard 8×8 chessboard?", answers: ["204"], hints: ["Count 1×1 squares, then 2×2, then 3×3, and so on up to 8×8, and add them all up.", "It's the sum of the squares from 1² up to 8²."], coinReward: 20 },
{ id: "logic_018", category: "logic", prompt: "Three friends split a $30 hotel bill, $10 each. The manager realizes the room was only $25 and sends the bellboy back with $5. The bellboy keeps $2 for himself and returns $1 to each friend. Now each friend paid $9 ($27 total), and the bellboy has $2 — that's $29. Where did the missing dollar go?", answers: ["there is no missing dollar", "no dollar is missing", "the math is a trick, nothing is missing"], hints: ["The $27 the friends paid already includes the bellboy's $2 inside it.", "Don't add the bellboy's $2 on top of the $27 — that's double-counting."], coinReward: 20 },
{ id: "logic_019", category: "logic", prompt: "What is the smallest number that is divisible evenly by every number from 1 to 10?", answers: ["2520"], hints: ["It has to be divisible by 8, 9, and 7 all at once, not just the small numbers.", "Multiply the highest powers of each prime up to 10: 2³ × 3² × 5 × 7."], coinReward: 20 },
{ id: "logic_020", category: "logic", prompt: "A jar contains only red and blue marbles. If you triple the number of blue marbles, blue marbles would outnumber red marbles by exactly as many as red currently outnumbers blue. If there are 20 marbles total, how many are blue?", answers: ["6", "6 blue"], hints: ["Let blue = b, red = 20 - b, and set up the equation from the description.", "3b - (20 - b) = (20 - b) - b — solve for b."], coinReward: 20 },
{ id: "logic_021", category: "logic", prompt: "Two trains start 300 miles apart and travel toward each other, one at 60 mph and the other at 40 mph. A bird starts at the front of one train, flying at 90 mph, and flies back and forth between the trains until they meet. How many total miles does the bird fly?", answers: ["270", "270 miles"], hints: ["First figure out how long it takes the trains to meet, ignoring the bird entirely.", "Once you know the time, the bird's total distance is just its speed × that time."], coinReward: 20 },
{ id: "logic_022", category: "logic", prompt: "A father is currently 4 times as old as his son. In 20 years, he will be exactly twice as old as his son. How old is the son right now?", answers: ["10", "10 years old"], hints: ["Let the son's age be x, so the father's age is 4x — write an equation for 20 years from now.", "4x + 20 = 2(x + 20) — solve for x."], coinReward: 20 },
{ id: "logic_023", category: "logic", prompt: "What is the sum of all whole numbers from 1 to 100?", answers: ["5050"], hints: ["Try pairing the first and last numbers: 1+100, 2+99, 3+98...", "Each pair adds up to 101, and there are 50 such pairs."], coinReward: 20 },
{ id: "logic_024", category: "logic", prompt: "A number is doubled, then increased by 5, giving a result of 17. What was the original number?", answers: ["6", "six"], hints: ["Work backward: subtract 5 from 17 first.", "Then divide what's left by 2."], coinReward: 20 },
{ id: "logic_025", category: "logic", prompt: "If today is Wednesday, what day of the week will it be exactly 100 days from now?", answers: ["friday"], hints: ["Divide 100 by 7 and look at the remainder.", "The remainder tells you how many days past Wednesday to count forward."], coinReward: 20 },
{ id: "logic_026", category: "logic", prompt: "You have an unmarked 3-liter jug and an unmarked 5-liter jug. Fill the 5-liter jug, pour it into the 3-liter jug until full, then empty the 3-liter jug and pour the remainder from the 5-liter jug into it. Refill the 5-liter jug completely, then top off the 3-liter jug from it. How many liters are left in the 5-liter jug at the end?", answers: ["4", "4 liters"], hints: ["After the first pour, the 5-liter jug has exactly 2 liters left in it.", "Once that 2 liters moves into the 3-liter jug, topping it off from a full 5-liter jug only takes 1 more liter."], coinReward: 20 },
{ id: "logic_027", category: "logic", prompt: "A book's pages are numbered from 1 to 100. How many total digits are used to print all the page numbers?", answers: ["192"], hints: ["Pages 1-9 use one digit each, pages 10-99 use two digits each — add those up first.", "Don't forget page 100 uses three digits by itself."], coinReward: 20 },
{ id: "logic_028", category: "logic", prompt: "I am a two-digit number. My digits add up to 9. If you reverse my digits, the new number is 45 more than me. What number am I?", answers: ["27"], hints: ["Let the tens digit be a and the ones digit be b, so a + b = 9.", "Reversing gives 10b + a, and that minus the original equals 45 — this simplifies to b - a = 5."], coinReward: 20 },
{ id: "logic_029", category: "logic", prompt: "A pizza is cut into 8 equal slices. If 3 friends share it as evenly as possible using only whole slices, how many slices does each friend get, and how many slices are left over?", answers: ["2 slices each, 2 left over", "2 each and 2 leftover", "2, 2"], hints: ["Divide 8 by 3 and think about the remainder, not a fraction.", "3 friends × 2 slices = 6 slices used — what's left of the 8?"], coinReward: 20 },
{ id: "logic_030", category: "logic", prompt: "What is the missing number in this pattern: 3, 9, 27, 81, ?", answers: ["243"], hints: ["Look at what each number is being multiplied by to get the next one.", "Each number is 3 times the one before it."], coinReward: 20 },

/* ============================================================ */
/* SITUATIONAL RIDDLE (20)                                       */
/* ============================================================ */
{ id: "situational_001", category: "situational", story: "A rare pen went missing from a locked office. Three employees were the last in the building: Marcus (accountant), Priya (receptionist), and Tom (janitor). Marcus said he left at 5 PM before the storm started. Priya said she was drenched from the rain when she left at 6:30. Tom said he was mopping the lobby all evening and never went near the office. The pen was found under a chair with muddy work-boot prints leading straight to the janitor's closet — prints that don't match Priya's heels or Marcus's dress shoes.", prompt: "Who most likely took the pen?", answers: ["tom", "the janitor"], hints: ["Compare the type of footprint to what each person would actually be wearing.", "One person's own boots are the exact match for the prints — despite their story of never leaving the lobby."], explanation: "The muddy prints were made by work boots, matching Tom's, not Priya's heels or Marcus's dress shoes. Despite claiming he never left the lobby, the boot prints place him right at the scene.", coinReward: 30 },
{ id: "situational_002", category: "situational", story: "The secret ingredient for a baking contest's winning pie was stolen from the judges' table before scoring. Hannah said she was washing bowls the whole time. David said he was outside on a phone call. Wei said he was chatting with the judges. Sofia said she never left her station, timing her second pie. When questioned, Sofia mentioned, 'It's not my fault the cinnamon got knocked over — I was nowhere near the judges' table.'", prompt: "Who most likely took the secret ingredient?", answers: ["sofia"], hints: ["Notice a detail one person knew about that they shouldn't have.", "Someone describes exactly what happened at the scene despite claiming they were never there."], explanation: "Sofia claimed she was never near the judges' table, yet she knew the cinnamon — the stolen ingredient — had been knocked over, a detail only someone actually present could know.", coinReward: 30 },
{ id: "situational_003", category: "situational", story: "A championship trophy vanished overnight from a locked display case at a school. The coach said he was home asleep by 10 PM. Captain Elena said she was at the library until it closed at 9. Captain Marcus said he grabbed his jacket from the gym around 8, then went home. The janitor said he cleaned the gym from 9 to 11 PM. Security footage shows the case light was still on at 11:30 PM — but the library, where Elena said she'd been, actually closes at 8:30 PM on weekdays, not 9.", prompt: "Whose story doesn't hold up?", answers: ["elena"], hints: ["Check what time each place mentioned would have actually been open.", "One person's claimed location couldn't have kept them there as long as they said."], explanation: "Elena said the library kept her until 9 PM, but it actually closes at 8:30 PM on weekdays — leaving a gap in her story right around when the trophy disappeared.", coinReward: 30 },
{ id: "situational_004", category: "situational", story: "A fire broke out in a warehouse storage room after hours. Ray, the supervisor, said he left at 8 PM after locking up. Talia, the clerk, said she came back at 9:45 for her laptop and left immediately. Ben, the security guard, said he only entered the storage room once, at 10 PM, when he noticed smoke and called it in. Investigators found the fire started from an electrical fault behind shelving rearranged that same night — and Ben's uniform sleeve was later found singed near the cuff.", prompt: "Who is most likely responsible for starting the fire, even if by accident?", answers: ["ben"], hints: ["Compare what each person says they touched to the physical evidence.", "One person's clothing shows signs of being near the fire earlier than they admitted."], explanation: "Ben claimed he only entered once, right when he reported the fire — but his singed sleeve suggests he was near it earlier, likely while moving the shelving that caused the fault.", coinReward: 30 },
{ id: "situational_005", category: "situational", story: "A final exam's answer key leaked online hours before the test. Omar said he only visited the teacher's office Monday. Lily said she visited Tuesday and Wednesday. Chen said he'd never been in the office all semester. Priya said she dropped off a permission slip Thursday. The leaked file's metadata shows it was created Wednesday afternoon from a computer inside the office — and the office sign-in log shows Chen's own signature at 1:15 PM that exact Wednesday.", prompt: "Who most likely leaked the exam?", answers: ["chen"], hints: ["Compare the leaked file's creation details to the sign-in records.", "One person made an absolute denial that a simple log directly contradicts."], explanation: "Chen insisted he'd never set foot in the office all semester, but the sign-in log places him there at 1:15 PM the exact Wednesday the leaked file was created.", coinReward: 30 },
{ id: "situational_006", category: "situational", story: "At a charity gala, a diamond necklace was stolen from its display case. Isabella said she only glanced at it from a distance. Marcus, an art dealer, said he examined it closely to appraise it, wearing gloves the whole time per protocol. Renée, the photographer, said she photographed the case from several angles but never touched anything. Security found a single fingerprint on the inside of the glass — a spot no photograph or glance could reach, and gloves would leave no print at all.", prompt: "Who most likely stole the necklace?", answers: ["renée", "renee"], hints: ["Think about who claimed to never touch anything, and whether that holds up.", "One person couldn't have left a print at all — who does that leave?"], explanation: "Marcus's gloves rule him out, and Isabella never got close enough to leave a print. That leaves Renée — despite saying she never touched anything, her print was found inside the case.", coinReward: 30 },
{ id: "situational_007", category: "situational", story: "The night before a big race, someone loosened a critical bolt on a rival team's car. Dana, the rival's own mechanic, said she was busy fixing her own car's brakes all night. Felix, a rookie driver, said he left early to rest. Grace, a track official, said she did her usual patrol and noted nothing unusual. The tampering used a torque wrench kept locked inside the rival team's own toolbox — a toolbox whose combination Grace had recorded during her official inspection that same week.", prompt: "Who most likely sabotaged the car?", answers: ["grace"], hints: ["Think about who would need access to a specific locked toolbox to use that tool.", "One person had a legitimate reason to know the combination through their job."], explanation: "The wrench came from the rival team's own locked toolbox. Felix had no access, and Dana had no reason to sabotage her own team. Grace, however, had recorded the combination during her inspection.", coinReward: 30 },
{ id: "situational_008", category: "situational", story: "An author's only copy of an unpublished manuscript vanished from her studio. Her assistant Ivy said she hadn't been to the studio in three days, out sick. Her neighbor Oscar said he stopped by once, as usual, to water the plants. The manuscript vanished on a Wednesday — and Ivy, despite claiming to be away for days, mentioned during questioning that the ending 'still needed work on the last chapter,' a detail only visible on the physical draft sitting on the studio desk.", prompt: "Who most likely took the manuscript?", answers: ["ivy"], hints: ["Notice a very specific detail one person shouldn't have known if they'd really been away.", "Someone commented on the manuscript's actual content despite claiming not to have seen it recently."], explanation: "Ivy claimed she hadn't been to the studio in three days, but she knew a specific detail about the unfinished ending — something only visible on the physical draft in the room.", coinReward: 30 },
{ id: "situational_009", category: "situational", story: "At a dinner party, a guest fell ill after drinking tea prepared by the host, Beatrice. Walter said he arrived just as tea was served and never went near the kitchen. Nancy, the host's sister, said she helped carry cups out, as she always does. Clive, a family doctor invited last-minute, said he hadn't touched any tea before examining the guest. Lab tests showed the tea contained a prescription-only sedative that matched what Clive carries in his medical bag — a bag he admitted leaving unattended in the kitchen.", prompt: "Who most likely poisoned the tea?", answers: ["clive"], hints: ["Think about who would have access to a specific prescription-only substance.", "One person's bag was left unattended in the exact room where the tea was prepared."], explanation: "The sedative matched what Clive carries as a doctor, and he admitted leaving his bag unattended in the kitchen — giving him both the means and the opportunity.", coinReward: 30 },
{ id: "situational_010", category: "situational", story: "A gallery discovered a painting on display had been swapped for a forgery during a private viewing. Lucas, the curator, said he only dusted the frame. Mireille, a restorer hired for touch-ups, said she inspected the canvas but never removed it from the wall. Henri, a collector, said he admired it from a chair the whole time. The forgery used a modern synthetic pigment that wouldn't have existed when the original was painted — later found on a rag inside Mireille's own restoration kit.", prompt: "Who most likely swapped the painting for a forgery?", answers: ["mireille"], hints: ["Think about who would have the skill and materials to create a convincing forgery.", "A specific modern material was found in one person's own equipment."], explanation: "The forgery's pigment was traced to a rag in Mireille's own kit — she had both the skill and the material, despite claiming she never took the painting off the wall.", coinReward: 30 },
{ id: "situational_011", category: "situational", story: "A prize-winning orchid disappeared from a botanical garden's locked greenhouse overnight. Head gardener Otis said he watered the greenhouse at 6 PM and left. Volunteer Nadia said she was cataloging seeds in the main office all evening. Visitor pass-holder Simon said he toured the outdoor gardens only, never the greenhouse. Soil matching the greenhouse's rare imported potting mix was later found on the floor mat of Simon's car — a mix not used anywhere else on the property.", prompt: "Who most likely stole the orchid?", answers: ["simon"], hints: ["Think about a very specific material that could only have come from one location.", "One person's own vehicle contained physical evidence tying them to a place they said they never entered."], explanation: "The greenhouse's rare imported soil mix isn't used anywhere else on the property, yet it turned up in Simon's car — despite his claim that he never went past the outdoor gardens.", coinReward: 30 },
{ id: "situational_012", category: "situational", story: "A food truck's secret sauce recipe, kept on an index card in a locked drawer, went missing before a big competition. Line cook Deja said she was on break the whole time. Owner Marcus said he was taking orders at the window all afternoon. New hire Theo said he'd never been shown where the recipes were kept. During questioning, Theo casually mentioned the sauce 'needed one more pinch of smoked paprika' — a tweak that only existed on the missing card, never in the sauce actually served that day.", prompt: "Who most likely took the recipe card?", answers: ["theo"], hints: ["Notice a very specific detail someone shouldn't know if they'd truly never seen the recipe.", "Compare what was in the day's actual sauce to what one person described."], explanation: "Theo claimed he'd never even been shown where the recipes were kept, yet he described an ingredient tweak that existed only on the missing card, not in the sauce actually served.", coinReward: 30 },
{ id: "situational_013", category: "situational", story: "A rare first-edition book vanished from a university's reading room, which requires a signed logbook to enter. Librarian Priyanka said she was reshelving in the back stacks all afternoon. Professor Nolan said he read at his usual table the whole time. Student Amara said she never made it past the front desk because the room 'looked closed.' The logbook shows Amara's own signature timestamped for that exact afternoon, seated at table 4 — right next to where the book had been displayed.", prompt: "Who most likely took the book?", answers: ["amara"], hints: ["Check the physical evidence against what each person claims about even entering the room.", "One person denies being somewhere the records directly place them."], explanation: "Amara claimed she never got past the front desk, but the logbook shows her signed in and seated at table 4 that exact afternoon — right beside where the book was on display.", coinReward: 30 },
{ id: "situational_014", category: "situational", story: "A prized racehorse's saddle was found deliberately damaged the morning of a big race. Trainer Estelle said she inspected all the tack the night before and it was fine. Stablehand Cody said he mucked out stalls and never touched the tack room. Jockey Reyes said he arrived that morning and went straight to warm-ups. A torn strap from the saddle was later found tangled in Cody's own jacket pocket, still smelling of the tack room's leather conditioner.", prompt: "Who most likely damaged the saddle?", answers: ["cody"], hints: ["Think about a piece of physical evidence that ended up somewhere it shouldn't have.", "One person claimed to have avoided a room entirely, yet carried something specific to it."], explanation: "Cody insisted he never touched the tack room, but a torn strap from the damaged saddle turned up in his own jacket pocket, still smelling of the room's leather conditioner.", coinReward: 30 },
{ id: "situational_015", category: "situational", story: "A community theater's opening-night costume was slashed hours before the show. Costume designer Ruth said she was steaming the other costumes backstage the whole time. Lead actor Devon said he was doing vocal warm-ups alone in his dressing room. Stagehand Priya said she was setting props on the far side of the stage, nowhere near costumes. Fabric fibers matching the slashed costume were found caught in a prop crate Priya had moved that afternoon — a crate stored directly beside the costume rack.", prompt: "Who most likely slashed the costume?", answers: ["priya"], hints: ["Think about where a specific piece of physical evidence was actually found.", "One person claimed to be nowhere near the costumes, yet evidence links directly to something they personally handled."], explanation: "Priya said she was nowhere near the costumes, but fabric fibers from the slashed costume were caught in a prop crate she'd personally moved — one stored right beside the costume rack.", coinReward: 30 },
{ id: "situational_016", category: "situational", story: "An apartment building's community garden had its prize tomato plants uprooted overnight. Resident Faye said she was out of town all week. Building super Reggie said he only checked the garden's sprinkler timer, briefly, at dusk. Neighbor Wallace said he never goes near the garden because of his allergies. Muddy gardening gloves, still damp, were found hanging in Wallace's own back porch the next morning — despite his claimed allergy to the exact plants that were uprooted.", prompt: "Who most likely uprooted the tomato plants?", answers: ["wallace"], hints: ["Think about physical evidence that contradicts someone's stated reason for staying away.", "One person's own porch held something incriminating and still fresh."], explanation: "Wallace claimed he avoided the garden entirely due to allergies, yet damp gardening gloves turned up on his own porch the very next morning.", coinReward: 30 },
{ id: "situational_017", category: "situational", story: "A small cruise ship's captain discovered the ship's safe had been opened and cash was missing overnight. First mate Delgado said he was on the bridge for his entire shift. Chef Odalys said she was prepping breakfast in the galley from 4 AM on. Passenger Whitfield said he was seasick in his cabin all night and never left. Security footage, however, shows someone matching Whitfield's build entering the crew corridor near the safe at 3:40 AM — a corridor passengers aren't supposed to have access to at all.", prompt: "Who most likely opened the safe?", answers: ["whitfield"], hints: ["Think about who had no legitimate reason to be somewhere, yet was caught on camera there anyway.", "One person's alibi directly contradicts footage of them in a restricted area."], explanation: "Whitfield claimed to be seasick in his cabin all night, but footage shows someone matching his build entering the restricted crew corridor near the safe at 3:40 AM.", coinReward: 30 },
{ id: "situational_018", category: "situational", story: "A small-town bakery's secret family recipe book went missing the same week a rival bakery opened nearby. Longtime baker Marisol said she'd had the book locked in her car the entire week. Apprentice Callum said he'd never been trusted with the book at all. Marisol's cousin Denise, visiting from out of town, said she just sat in the shop's back office reading a magazine. The rival bakery's new signature bread turned out to use a highly unusual spice blend appearing nowhere else — except in one handwritten recipe from Marisol's book, which Denise had access to in that same back office.", prompt: "Who most likely leaked the recipe to the rival bakery?", answers: ["denise"], hints: ["Think about who had unsupervised access to the book despite claiming to just be reading.", "A very specific, unusual detail from the recipe turned up somewhere it shouldn't have."], explanation: "Denise claimed she was just reading in the back office, but that's exactly where the recipe book was accessible — and the rival bakery's bread used an unusual spice blend unique to one recipe in that book.", coinReward: 30 },
{ id: "situational_019", category: "situational", story: "A hospital's break room reported a locked medicine cabinet tampered with overnight. Night nurse Wren said she did her usual rounds and never went near the break room. Orderly Hutch said he was restocking supplies on a different floor all shift. Visiting relative Callahan said he waited quietly in the family lounge the entire night. Cabinet access requires a keycard swipe, and the digital log shows Wren's own keycard used at 2:14 AM — a swipe she insists she never made.", prompt: "Who most likely tampered with the cabinet?", answers: ["wren"], hints: ["Think about what kind of access the cabinet actually requires, and who has it.", "A digital record directly contradicts someone's denial."], explanation: "Only a keycard could open the cabinet, and the digital log shows Wren's own card swiped at 2:14 AM — directly contradicting her claim that she never went near the break room.", coinReward: 30 },
{ id: "situational_020", category: "situational", story: "A small vineyard's aged wine barrel was found drained the morning before a big tasting event. Owner Genevieve said she checked the cellar at closing and everything was fine. Cellar hand Théo said he was in town running errands all evening. Wine critic Ashford, invited early for a private preview, said he only tasted from the tasting room, never entering the cellar. Genevieve's dog was later found with wine-stained paws — having been let outside by someone that evening, since Genevieve herself never leaves the dog out after dark, and only Ashford had been alone with the dog near the cellar door earlier that day.", prompt: "Who most likely drained the barrel?", answers: ["ashford"], hints: ["Think about who had unsupervised time near the cellar despite denying they entered it.", "An unusual clue about the dog points to who else was near the cellar door that day."], explanation: "Ashford claimed he never entered the cellar, but he was the only one alone near the cellar door that day — and the dog, who Genevieve never lets out after dark, ended up outside with wine-stained paws on his watch.", coinReward: 30 }

];

/* ============================================================ */
/* ENGINE                                                         */
/* ============================================================ */

// Placeholder until the real Echo Coins economy (from echovault-progression
// planning) is built into script1.js — keeps a running localStorage total
// so Riddle Den is fully testable now. Safe to delete once the real
// creditEchoCoins() exists elsewhere; this only defines it if missing.
if (typeof creditEchoCoins !== "function") {
  window.creditEchoCoins = function (amount) {
    const current = parseInt(localStorage.getItem("echoCoins") || "0", 10);
    localStorage.setItem("echoCoins", current + amount);
  };
}

function normalizeAnswer(str) {
  return str.toLowerCase().trim().replace(/[^\w\s]/g, "");
}

function checkAnswer(riddle, input) {
  const normalizedInput = normalizeAnswer(input);
  return riddle.answers.some(a => normalizeAnswer(a) === normalizedInput);
}

function getCoinReward(riddle, hintsUsed, gaveUp) {
  if (gaveUp) return Math.round(riddle.coinReward * 0.1);
  if (hintsUsed === 0) return riddle.coinReward;
  if (hintsUsed === 1) return Math.round(riddle.coinReward * 0.6);
  return Math.round(riddle.coinReward * 0.3); // 2 hints used
}

// riddleProgress stored in the Attic's own IndexedDB, keyed by riddle id
// { solved: bool, attempts: n, hintsUsed: n, gaveUp: bool, coinsEarned: n }

function submitRiddleAnswer(riddle, input, progress) {
  if (progress.solved) return { alreadySolved: true };

  progress.attempts++;
  const config = RIDDLE_CATEGORIES[riddle.category];
  const correct = checkAnswer(riddle, input);

  if (correct) {
    progress.solved = true;
    progress.coinsEarned = getCoinReward(riddle, progress.hintsUsed, false);
    creditEchoCoins(progress.coinsEarned); // hooks into the progression system
    return { correct: true, coinsEarned: progress.coinsEarned, explanation: riddle.explanation || null };
  }

  const hintIndexToShow = config.triesBeforeHint.filter(t => progress.attempts >= t).length - 1;
  const newHintAvailable = hintIndexToShow >= progress.hintsUsed;
  const showReveal = progress.attempts >= config.triesBeforeReveal;

  return { correct: false, newHintAvailable, showReveal, attempts: progress.attempts };
}

function giveUpOnRiddle(riddle, progress) {
  progress.solved = true;
  progress.gaveUp = true;
  progress.coinsEarned = getCoinReward(riddle, progress.hintsUsed, true);
  creditEchoCoins(progress.coinsEarned);
  return { answer: riddle.answers[0], explanation: riddle.explanation || null, coinsEarned: progress.coinsEarned };
}
